#!/bin/bash
#==============================================================================
# Copyright (C) 2023-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# Ensure flight_ROOT is set correctly
flight_ROOT=/opt/flight

# Run the migration
"${flight_ROOT}/bin/ruby" <<EOF
require 'yaml'
require 'fileutils'

install_dir = "${flight_ROOT}/opt/hunter"

Dir.chdir install_dir do
  ['buffer', 'parsed'].each do |list|
    list_file = File.join('var', "#{list}.yaml")
    next unless File.file?(list_file)

    old = YAML.load_file(list_file)

    next unless old # Empty file

    dir = FileUtils.mkdir_p(File.join(install_dir, 'var', list)).first

    old.each do |node|
      out = YAML.dump(node)
      File.open(File.join(dir, "#{node['id']}.yaml"), "w") do |f|
        f.write(out)
      end
    end

    FileUtils.rm(list_file)
  end
end
EOF
