#!/bin/sh
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# Checks if the example config pack has been previously installed
# and symlinks it into place if required
dir=/opt/flight/opt/www/landing-page/default/content/config-packs/
flag="$dir/.example-installed"
if [ ! -f "$flag" ]; then
  touch "$flag"
  pushd "$dir" >/dev/null
  ln -s example.md.disabled example.md
  popd >/dev/null
fi

# `flight-www` may not be installed yet.  That is fine, as `flight-www` will
# compile the landing page once it is installed.
if [ -f /opt/flight/libexec/commands/landing-page ]; then
    /opt/flight/bin/flight landing-page compile
fi

exit 0
