#!/bin/bash
#==============================================================================
# Copyright (C) 2021-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# Ensure flight_ROOT is set correctly
flight_ROOT=/opt/flight

# Generate a private key if required
priv_key=${flight_ROOT}/etc/job/id_rsa
pub_key="$priv_key".pub
if [ ! -f "$priv_key" ]; then
  mkdir -p $(dirname "$priv_key")
  ssh-keygen -b 4096 -t rsa -f "$priv_key" -q -N "" -C "Flight Job Key"
  chmod o+r "$priv_key"

  # Ensure any existing public key is removed
  rm -f "$pub_key"
fi

# Generate the public key if required
if [ ! -f "$pub_key" ]; then
  mkdir -p $(dirname "$pub_key")
  ssh-keygen -y -f "$priv_key" > "$pub_key"
fi

exit 0
