#!/bin/sh
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# Update the session secret if unset
cat <<RUBY | /opt/flight/bin/ruby
require 'json'
require 'securerandom'

# Load the existing config
path = File.join(ENV['flight_ROOT'], 'opt/console-api/etc/config.json')
data = JSON.load File.read(path)

# Update the secret if unset
if data["session"]["secret"].to_s.empty?
  data["session"]["secret"] = SecureRandom.base64(20)

  # Save the config
  File.write(path, JSON.pretty_generate(data))
end
RUBY

# Generate a private key if required
priv_key=/opt/flight/etc/console-api/id_rsa
if [ ! -f "$priv_key" ]; then
  mkdir -p $(dirname "$priv_key")
  ssh-keygen -b 4096 -t rsa -f "$priv_key" -q -N "" -C "Flight Console API Key"
fi

# Generate the public key if required
pub_key=/opt/flight/etc/ssh/authorized_keys.d/console-api
if [ ! -f "$pub_key" ]; then
  mkdir -p $(dirname "$pub_key")
  ssh-keygen -y -f "$priv_key" > "$pub_key"
fi

/opt/flight/bin/flight service reload www 1>/dev/null 2>&1
exit 0
