#!/bin/sh
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================
if [ ! -f /opt/flight/opt/power-client/etc/config.yaml ] ; then
    cat << EOF > /opt/flight/opt/power-client/etc/config.yaml
base_url: http://power-server-ip:port
jwt_token: generated_authorisation_token
EOF
    echo "=============================================="
    echo "Update the config file at:"
    echo "  /opt/flight/opt/power-client/etc/config.yaml"
    echo
    echo "It should contain the following keys:"
    echo "  base_url: http://power-server-ip:port"
    echo "  jwt_token: generated_authorisation_token"
    echo "These will need to be amended to reflect the"
    echo "power-server configuration and keys"
    echo "=============================================="
fi

exit 0
