#!/bin/sh
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# If upgrading from an older version landing page overrides will be in the
# wrong location.
if [ -d /opt/flight/opt/landing-page/www/overridden ]; then
    echo "Syncing old landing-page overrides"
    rsync -a /opt/flight/opt/landing-page/www/overridden \
             /opt/flight/opt/www/landing-page/
fi

/opt/flight/bin/flight landing-page compile

if [ -f /opt/flight/etc/cron/daily/flight-www-auto-cert-renewal ]; then
  cat <<EOF
SSL certificates are currently configured to be checked for renewal daily.
This may be too frequent and there is a small chance that this could cause
issues.  You should consider changing this to a weekly check.  To do so run
the following:

/opt/flight/bin/flight www cron-renewal --disable
sed -i -e '/cron_path/s/daily/weekly/' /opt/flight/etc/share/cert.yaml
/opt/flight/bin/flight www cron-renewal
EOF
fi

exit 0
