#!/bin/sh
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# If upgrading from an older version landing page overrides will be in the
# wrong location.
if [ -d /opt/flight/opt/landing-page/www/overridden ]; then
    echo "Syncing old landing-page overrides"
    rsync -a /opt/flight/opt/landing-page/www/overridden \
             /opt/flight/opt/www/landing-page/
fi

/opt/flight/bin/flight landing-page compile

# Handles upgrading from the old cert.yaml to the new www.yaml
old=/opt/flight/etc/share/cert.yaml
new=/opt/flight/etc/share/www.yaml
if [ -f "$old" ]; then
  # Attempts to disable cron with the old config
  cp "$old" "$new"
  /opt/flight/bin/flight www cron-renewal --disable >/dev/null 2>&1
  disabled_cron="$?"
  rm -f "$new"

  # Extracts the relevant portions of the old config to the new one
  cat "$old" | grep ^email >> "$new"
  cat "$old" | grep ^domain >> "$new"
  cat "$old" | grep ^cert_type >> "$new"
  cat <<EOF
The configuration defaults have changed since the previous release. Please review the following:
$new
$old.rpmsave
/opt/flight/opt/www/cert/etc/config.reference
EOF

  # Re-enables cron with the new config if required
  if [ "$disabled_cron" -eq 0 ]; then
    /opt/flight/bin/flight www cron-renewal >/dev/null 2>&1
  fi
fi

exit 0
