#!/bin/sh
#==============================================================================
# Copyright (C) 2020-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# If upgrading from an older version landing page overrides will be in the
# wrong location.
if [ -d /opt/flight/opt/landing-page/www/overridden ]; then
    echo "Syncing old landing-page overrides"
    rsync -a /opt/flight/opt/landing-page/www/overridden \
             /opt/flight/opt/www/landing-page/
fi

/opt/flight/bin/flight landing-page compile


# Rename the cron file used for automatic cert renewal.
find /opt/flight/etc/cron -name flight-www-auto-cert-renewal -print0 \
    | xargs -0 -I %file% sh -c 'mv %file% $(dirname %file%)/cert-renewal'

if [ -f /opt/flight/etc/cron/daily/cert-renewal ]; then
  cat <<EOF
SSL certificates are currently configured to be checked for renewal daily.
This may be too frequent and there is a small chance that this could cause
issues.  You should consider changing this to a weekly check.  To do so:

1. Delete the file /opt/flight/etc/cron/daily/cert-renewal
2. Edit the flight cert configuration file /opt/flight/etc/cert.yaml
   and ensure the `cron_path` is set to use the weekly directory.
3. Run /opt/flight/bin/flight www cron-renewal
EOF
fi

# If upgrading from an older version, the certificate generation configuration
# will be in the wrong location.
if [ -f /opt/flight/etc/share/cert.yaml ]; then 
    echo "Found existing flight-cert configuration"
    script=$(cat <<EOF
          puts YAML.load_file('/opt/flight/etc/share/cert.yaml').
              slice('email', 'domain', 'cert_type').
              reduce('') { |accum, k|
                  accum << " --#{k[0].gsub(/_/, '-')} #{k[1].nil? ? '' : k[1]}"
              }
EOF
)
    saved_config=$(/opt/flight/bin/flexec ruby -ryaml -e "${script}")
    echo "Updating flight-cert configuration: ${saved_config}"
    /opt/flight/bin/flight www cert-gen --config-only ${saved_config}
fi

exit 0
