#!/bin/sh
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================
echo "Creating log and config directories"
mkdir -p /opt/flight/{etc,log}

echo "Setting up systemd service"
cp -vf /opt/flight/opt/power-server/support/power-server.service /usr/lib/systemd/system/ 

if [ ! -f /opt/flight/etc/power-server.conf ] ; then
    echo "Generating app secret key"
    echo "jwt_shared_secret='$(openssl rand -base64 16)'" > /opt/flight/etc/power-server.conf
    echo "topology_config=/opt/flight/etc/power-server/topology.yaml" >> /opt/flight/etc/power-server.conf
fi

if [ ! -f /opt/flight/etc/power-server/topology.yaml ] ; then
    echo "Creating topology.yaml and adding example nodes"
    mkdir -p /opt/flight/etc/power-server/
    cp /opt/flight/opt/power-server/config/topology.example.yaml /opt/flight/etc/power-server/topology.yaml
    cat << EOF > /opt/flight/etc/power-server/topology.yaml
static_nodes:
  node01:
    platform: aws
    ec2_id: i-node01xxxxxxxxxxx
    region: eu-west-1
  node02:
    platform: azure
    resource_group: demo-power-group
  node03:
    platform: ipmi
    ipmi_username: admin
EOF
fi

exit 0
