#!/bin/sh
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# This should be removed once the version is released
cat <<EOF
The machine type definitions have changed with this release.  The previous
definitions were:

  general-small      -> t2.small
  general-large      -> t2.large
  compute-2C-3.75GB  -> c4.large
  compute-8C-15GB    -> c4.2xlarge
  gpu-1GPU-8C-61GB   -> p3.2xlarge
  gpu-4GPU-32C-244GB -> p3.8xlarge

The new definitions are:

  general-small  -> t3.medium
  general-medium -> t3.xlarge
  general-large  -> t3.2xlarge
  compute-small  -> c5.large
  compute-medium -> c5.xlarge
  compute-large  -> c5.2xlarge
  gpu-small      -> p3.2xlarge
  gpu-medium     -> p3.8xlarge
  gpu-large      -> p3.16xlarge
  mem-small      -> r5.large
  mem-medium     -> r5.xlarge
  mem-large      -> r5.2xlarge

Your nodes have not been changed.  You may wish to consider changing your
nodes accordingly.  This can be done by running:

  /opt/flight/bin/flight estate change NODE

EOF
