#!/bin/bash
#==============================================================================
# Copyright (C) 2021-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# NOTE: This file is managed by 'update_web_suite_package_scripts' software
#       definition. Any changes will be lost on the next build.

# Run the configuration
# Migrate the old files from usr/share to var/lib
old=/opt/flight/usr/share/file-manager-api
new=/opt/flight/var/lib/file-manager-api
if ls "$old" >/dev/null 2>&1; then
  mkdir -p "$new" >/dev/null
  ls "$old" | xargs -I {} mv "$old/{}" "$new"
  rmdir "$old"
fi

# Added for best practive
/opt/flight/bin/flight service configure --force file-manager-api >/dev/null 2>&1

# Check if the service is already running and restart it
if /opt/flight/bin/flight service status file-manager-api | grep active >/dev/null 2>&1 ; then
  /opt/flight/bin/flight service restart file-manager-api >/dev/null 2>&1
fi

# Reload flight-www to pick up the new config
/opt/flight/bin/flight service reload www 1>/dev/null 2>&1

exit 0
