#!/bin/bash
#==============================================================================
# Copyright (C) 2021-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# NOTE: This file is managed by 'update_web_suite_package_scripts' software
#       definition. Any changes will be lost on the next build.

# Ensure flight_ROOT is set correctly
flight_ROOT=/opt/flight

# Run the configuration
# Migrate the old files from usr/share to var/lib
old=${flight_ROOT}/usr/share/file-manager-api
new=${flight_ROOT}/var/lib/file-manager-api
if ls "$old" >/dev/null 2>&1; then
  mkdir -p "$new" >/dev/null
  ls "$old" | xargs -I {} mv "$old/{}" "$new"
  rmdir "$old"
fi

# Warn about obsolete configuration.
env_file=${flight_ROOT}/etc/service/env/file-manager-api
var_name="flight_FILE_MANAGER_API_cloudcmd_cookie_domain"
if [ -f "${env_file}" ] && grep -q "^${var_name}=" "${env_file}" ; then
    # There is existing obsolete configuration for the domain name.
    domain=$(grep "^${var_name}=" "${env_file}" | cut -d= -f2)
    cat <<EOF 1>&2

===========================================================
WARNING: Configuration required for flight-file-manager-api
===========================================================

The existing configuration of 'cloudcmd_cookie_domain' for
flight-file-manager-api is no longer supported.  To maintain the configuration
follow one of the options below and then restart flight-file-manager-api.

Run the command:

    flight config set web-suite.domain "${domain}"

Or edit the configurtion file '${flight_ROOT}/etc/file-manager-api.yaml' and
set 'cloudcmd_cookie_domain' to '${domain}'.

EOF
    # Delete the unused configuration.
    sed -i \
        -e "/^${var_name}=/i # Setting ${var_name} in this file is no longer supported.  The following line can be safely removed." \
        -e "/^${var_name}=/s/^/# /" \
        "${env_file}"
fi

${flight_ROOT}/bin/flight service configure file-manager-api --force --config '{}' >/dev/null 2>&1

# Check if the service is already running and restart it
if ${flight_ROOT}/bin/flight service status file-manager-api | grep active >/dev/null 2>&1 ; then
  ${flight_ROOT}/bin/flight service restart file-manager-api >/dev/null 2>&1
fi

# Reload flight-www to pick up the new config
${flight_ROOT}/bin/flight service reload www 1>/dev/null 2>&1

exit 0
