#!/bin/bash
#==============================================================================
# Copyright (C) 2021-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================

# NOTE: This file is managed by 'update_web_suite_package_scripts' software
#       definition. Any changes will be lost on the next build.

# Ensure flight_ROOT is set correctly
flight_ROOT=/opt/flight

# Run the configuration
secret_file=${flight_ROOT}/etc/shared-secret.conf
if [ ! -f "${secret_file}" ] ; then
    date +%s.%N | sha256sum | cut -c 1-40 > "${secret_file}"
    chmod 0400 "${secret_file}"
fi

# Added for best practice
${flight_ROOT}/bin/flight service configure login-api --force --config '{}'

# Check if the service is already running and restart it
if ${flight_ROOT}/bin/flight service status login-api | grep active >/dev/null 2>&1 ; then
  ${flight_ROOT}/bin/flight service restart login-api >/dev/null 2>&1
fi

# Reload flight-www to pick up the new config
${flight_ROOT}/bin/flight service reload www 1>/dev/null 2>&1

exit 0
