#!/bin/sh
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================
if [ -f /etc/redhat-release ]; then
  if grep -q 'release 8' /etc/redhat-release; then
    cat <<EOF 1>&2
========================================
Optional Dependencies for Flight Desktop
========================================
For screen capture support, please install 'xorg-x11-apps' (requires PowerTools)
and 'netpbm-progs'.
EOF
  else
    cat <<EOF 1>&2
========================================
Optional Dependencies for Flight Desktop
========================================
For better desktop session passwords, please install 'apg' (requires EPEL).
For websocket support, please install 'python-websockify' (requires EPEL).
For screen capture support, please install 'xorg-x11-apps' and 'netpbm-progs'.
EOF
  fi
else
  cat <<EOF 1>&2
========================================
Optional Dependencies for Flight Desktop
========================================
For better desktop session passwords, please install 'apg'.
For websocket support, please install 'websockify'.
For screen capture support, please install 'x11-apps' and 'netpbm'.
EOF
fi

exit 0
