#!/bin/sh
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================
mkdir -p "${flight_ROOT:-/opt/flight}"/opt/action-api/libexec/

flight service info action-api | while read line; do
  # Find the jwt_secret line
  if [ "$(echo "$line" | cut -f2)" == "jwt_secret" ]; then
    if [ -z "$(echo "$line" | cut -f4)" ]; then
      # Configure it with a random string if unset
      secret=$( echo $(hostname --fqdn).$(date  +%s.%N) | sha256sum | cut -c 1-40 )
      payload="{ \"jwt_secret\": \"$secret\" }"
    else
      # Ensure the application is reconfigured even if nothing has changed
      payload="{}"
    fi
    echo "$payload" | flight service configure action-api --force --config @- >/dev/null
  fi
done

/opt/flight/bin/flight service reload www 1>/dev/null 2>&1
exit 0
