#!/bin/sh
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of OpenFlight Omnibus Builder.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# This project is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with this project. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on OpenFlight Omnibus Builder, please visit:
# https://github.com/openflighthpc/openflight-omnibus-builder
#===============================================================================
mkdir -p "${flight_ROOT:-/opt/flight}"/opt/action-api/libexec/

# The application needs an authentication secret which can be used to "sign"
# the JWT tokens it creates.  This needs to be globally uniq, but otherwise
# has no particular format.
#
# Unfortunately, `flight service configure SERVICE` does not have a
# non-interactive mode.  We do our best to emulate such a thing here. 
#
config_file="${flight_ROOT:-/opt/flight}"/var/lib/service/action-api.yml
if [ ! -f "${config_file}" ]; then
    mkdir -p "$(dirname "${config_file}")"
    secret=$( echo $(hostname --fqdn).$(date  +%s) | md5sum | cut -f1 -d' ')
    cat <<EOF > "${config_file}"
---
jwt_secret: ${secret}
EOF
    flight_ROOT="${flight_ROOT:-/opt/flight}" /bin/bash \
        "${flight_ROOT:-/opt/flight}"/etc/service/types/action-api/configure.sh \
        jwt_secret="${secret}"
fi
exit 0
