---
title: "Flight desktop access service client"
text: |
  Please provide values for the following configuration items.

  Cluster name: The human-friendly name of the cluster.
  Cluster description: A human-friendly description of the cluster.  This could be used to describe its purpose or the features that it supports.
  Cluster logo: The URL of a logo for the cluster.  Leave blank to not use a logo.
  Hostname or IP: The hostname or IP address for this cluster.

values:
  - key: clusterName
    label: Cluster name
    value: ''
    length: 32

  - key: clusterDescription
    label: Cluster description
    value: ''
    length: 512

  - key: clusterLogo
    label: Cluster logo
    value: ''
    length: 512

  - key: hostname
    label: Hostname or IP
    value: ''
    length: 128
